#!/bin/bash

file=$*

if [[ $(pgrep mpv) ]] && [[ -S /tmp/mpv.socket ]]; then
    echo "loadfile \"${file}\" append-play" | socat - /tmp/mpv.socket
else
    rm -f /tmp/mpv.socket
    mpv --x11-name=queue --title=queue --input-ipc-server=/tmp/mpv.socket --no-terminal --force-window=yes "$file" &
fi
